#!/bin/sh

set -e

# verify this is for us or exit gracefully
if [ "$(readlink '/system-update')" != '/var/cache/pacman/pkg' ]; then
	exit 0
fi

# remove triggering symlink
rm -f /system-update

# install updates
pacman -Su --noconfirm

# clean up package cache
pacman -Sc --noconfirm

# reboot
systemctl reboot
